apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crud-api
  labels:
    cloud.googleapis.com/location: {{GCP_REGION}}
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cloudsql-instances: {{DB_INSTANCE_CONNECTION_NAME}}
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      # Conteneur principal - API CRUD
      - name: crud-api
        image: docker.io/{{DOCKERHUB_USERNAME}}/crud-api:{{VERSION}}
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: "127.0.0.1"  # Via Cloud SQL Proxy
        - name: DB_NAME
          value: "{{DB_NAME}}"
        - name: DB_USER
          value: "{{DB_USER}}"
        - name: DB_PASSWORD
          value: "{{DB_PASSWORD}}"
        - name: LOG_DIR
          value: "/var/logs/crud"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /var/logs/crud

      # Conteneur sidecar - Cloud SQL Proxy
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
        - "--structured-logs"
        - "--port=3306"
        - "{{DB_INSTANCE_CONNECTION_NAME}}"
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true

      # Conteneur sidecar - Fluent Bit pour les logs
      - name: fluent-bit
        image: docker.io/{{DOCKERHUB_USERNAME}}/fluent-bit-custom:{{VERSION}}
        env:
        - name: LOKI_HOST
          value: "{{LOKI_HOST}}"
        - name: LOKI_PORT
          value: "{{LOKI_PORT}}"
        - name: LOKI_JOB_LABEL
          value: "crud-api-cloudrun"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: logs
          mountPath: /var/logs/crud
          readOnly: true

      volumes:
      - name: logs
        emptyDir: {}
