FROM fluent/fluent-bit:4.0.13

# Copier les fichiers de configuration
COPY fluent-bit.conf /fluent-bit/etc/fluent-bit.conf
COPY parsers.conf /fluent-bit/etc/parsers.conf

# Commande par défaut (on enlève les commandes USER et mkdir qui peuvent causer des problèmes)
CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]